enum Language {
  zh(
    name: "简体中文",
    map: {
      "sensor_off": "传感器关闭",
      'sensor_on': "传感器开启",
      "lang": "简体中文",
      "locale": "zh_CN",
      "title": "流光 · 记",
      "home_page": "流光 · 记",
      "pick_null": "请选择",
      "set_lang": "当前语言（点击切换）",
      "set_night": "夜间模式",
      "set_ver": "版本号",
      "set_pub": "发布日期",
      "set_cache": "清除缓存",
      "set_tab1": "显示",
      "set_tab2": "视频",
      "set_tab3": "应用",
      "set_tab4": "帮助",
      "gen_top": "生成自",
      "gen_pic": "图片",
      "gen_text": "文本",
      "gen_video": "视频",
      "gen_tip_pic": "请选择图片文件 (小于[FILE_SIZE])",
      "gen_tip_text": "请输入描述文本",
      "gen_tip_video": "请选择视频文件\n(大小 1.5 GB 以内，\n拍摄时长 10min 以内)",
      "gen_tip_textbox": "在此处键入文本",
      "gen_button": "生成记忆",
      "gen_shot": "拍照",
      "gen_gallery": "从相册中选择",
      "gen_cancel": "取消",
      "reco_tip_title1": "一、设备与设置",
      "reco_tip_title2": "二、拍摄环境与操作",
      "reco_tip_title3": "三、后期检查",
      "reco_tip1": """设备：使用支持1080p/30fps录像的智能手机或相机。
稳定：建议使用三脚架，避免画面抖动。
分辨率与帧率：在设置中手动选择 1920×1080（1080p） 和 30fps。
曝光：使用自动曝光模式。如光线明暗变化大，可手动锁定曝光。
对焦：使用自动连续对焦模式。""",
      "reco_tip2": """光线：在光线均匀、充足的条件下拍摄。避免逆光（如背景是窗户）。
动作：拍摄时，尽量避免快速移动或晃动相机。
内容：规划不同的拍摄内容和角度，避免画面重复。""",
      "reco_tip3": """如视频使用手机自带相机软件拍摄，请用剪辑软件（如剪映）检查视频，剪掉抖动、模糊或过曝的片段。
最终导出时，确认参数为 1080p 和 30fps。""",
      "reco_camun": "相机访问被拒绝。\n请在系统设置中启用相机权限。",
      "set_open_settings": "前往设置",
      "reco_wait": "相机初始化中...",
      "recall": "回忆",
      "record": "相机记录",
      "generate": "图文生成",
      "community": "社区",
      "settings": "设置",
      "manage": "管理",
      "tip_unava": "该功能尚未开放，敬请期待！",
      "tip_oversize": "上传的文件太大了！",
      "tip_overquan": "你上传的文件太多了！",
      "tip_cache": "已成功清除缓存",
      "tip_fail": "文件上传失败！",
      "tip_no_permission": "应用没有权限，无法保存到图库。",
      "recall_search_hint": "搜索回忆...",
      "recall_empty_title": "暂无回忆，去记录一些美好瞬间吧",
      "recall_open_demo": "打开本地离线 Demo 模型",
      "recall_no_desc": "没有描述信息",
      "recall_demo_title": "本地 Demo 模型 (离线可用)",
      "recall_demo_desc": "预置的 3DGS 模型，无需网络即可查看。",
      "recall_error_offline": "加载模型失败，已切换至离线模式",
      "recall_error_search": "搜索失败: ",
      "recall_refresh": "刷新",
      "recall_local_rag": "端侧隐私检索",
      "recall_cloud_rag": "云端语义检索",
      "recall_local_ai_rag": "本地 AI 问答",
      "recall_agent_rag": "空间记忆智能管理",
      "recall_search_mode": "检索模式",
      "recall_search_mode_desc": "选择当前搜索栏优先启用的记忆检索与智能管理方式。",
      "recall_local_ready": "索引已就绪",
      "recall_local_indexing": "正在本地建立向量索引…",
      "recall_local_scope": "搜索词不会上传到云端",
      "recall_local_ai_scope": "问题先检索本地记忆，再交给端侧模型回答",
      "recall_agent_scope": "连接 Supabase Deno LangChain 工具链，对三维记忆进行检索、定位、分析与后续操作",
      "recall_local_empty": "本地索引中没有命中结果",
      "recall_cloud_scope": "搜索词将发送到云端大模型",
      "recall_cloud_empty": "云端语义检索没有命中结果",
      "recall_local_ai_empty": "本地 AI 没有检索到可用于回答的记忆片段",
      "recall_agent_empty": "输入空间问题或管理指令，Agent 会结合多工具链处理三维记忆任务",
      "recall_local_ai_hint": "输入问题，基于本地记忆问答...",
      "recall_agent_hint": "输入空间问题或管理指令",
      "recall_agent_panel_hint": "输入空间问题或管理指令后按回车，Agent 会调用多种工具完成三维记忆检索、定位与管理。",
      "agent_status_connecting": "正在连接 Agent...",
      "agent_status_stopped": "已停止 Agent 执行",
      "agent_status_stopped_summary": "用户手动停止了本次 Agent 执行",
      "agent_status_force_interrupted": "用户已强行中断 Agent",
      "agent_status_final_answer_ready": "最终回答已生成",
      "agent_status_plan_ready": "已生成执行计划",
      "agent_status_tool_start": "开始执行工具",
      "agent_status_waiting_tool_result": "等待工具返回结果",
      "agent_status_tool_result_ready": "工具已返回结果",
      "agent_status_generating_final_answer": "正在生成最终回答",
      "agent_status_execution_failed": "Agent 执行失败",
      "agent_status_request_started": "正在发起 Agent 流式请求",
      "agent_status_stream_fallback": "流式连接失败，准备回退到普通请求",
      "agent_status_stream_start_fallback": "流式启动失败，准备回退到普通请求",
      "agent_status_single_response_fallback": "当前环境不支持流式事件，已回退到一次性回答",
      "agent_status_tool_call": "调用工具",
      "agent_status_tool_args": "调用参数",
      "agent_status_tool_unnamed": "未命名工具",
      "agent_status_warming_up": "正在唤醒神经引擎...",
      "agent_status_reviewing_context": "正在查阅相关资料...",
      "agent_status_deep_thinking": "正在深度思考...",
      "agent_action_copy": "复制",
      "agent_action_stop": "停止",
      "agent_action_code_copied": "代码已复制",
      "agent_elapsed_running": "Agent 已运行 {duration}",
      "agent_elapsed_finished": "本次 Agent 总耗时 {duration}",
      "agent_search_failed": "Agent 智能管理失败",
      "agent_stream_failed": "Agent 流式连接失败（尝试回退）",
      "agent_stream_start_failed": "Agent 流式启动失败（尝试回退）",
      "agent_error_empty_query": "查询语句不能为空",
      "agent_error_missing_supabase_url": "未配置 SUPABASE_URL，无法建立 Agent 流式连接",
      "agent_error_bad_response": "agent-recall 返回格式错误",
      "agent_error_unavailable": "agent-recall 当前不可用（HTTP 503）。这通常表示 Edge Function worker 启动失败，或上游模型网关暂时不可用。请优先检查 Supabase Edge Function 日志。",
      "agent_error_upstream": "agent-recall 上游服务响应异常，请检查 Edge Function 日志和模型网关配置",
      "agent_error_http": "agent-recall 调用失败（HTTP {status}）",
      // 任务列表页面
      "task_list_title": "记忆任务",
      "task_list_empty_title": "暂无任务",
      "task_list_empty_desc": "开始记录您的第一个记忆吧！",
      "status_pending": "等待处理",
      "status_processing": "处理中",
      "status_completed": "已完成",
      "status_failed": "处理失败",
      "error_not_logged_in": "请先登录",
      "error_fetch_tasks": "获取任务失败",
      "error_title": "发生错误",
      "error_unknown": "未知错误",
      "retry": "重试",
      "refresh": "刷新",
      "task_status_pending": "任务等待处理中...",
      "task_status_processing": "任务正在处理中...",
      "task_status_completed": "任务已完成",
      "task_status_failed": "任务处理失败",
      "task_status_unknown": "任务状态未知",
      // 任务通知弹窗
      "task_completed": "个任务已完成",
      "task_failed": "个任务失败",
      "task_notification_completed": "个记忆任务已完成，点击查看",
      "task_notification_failed": "个记忆任务处理失败，点击查看",
      "logs_collapse": "收起日志",
      "logs_expand": "展开日志",
      // Generate page
      "gen_upload_progress": "上传 %s%",
      "gen_waiting_material": "等待素材",
      "gen_ready_submit": "可提交",
      "gen_section_image": "图像输入",
      "gen_section_text": "文本草稿",
      "gen_section_video": "视频采集",
      "gen_subtitle": "把素材、状态和提交动作压进同一条生成流程里，不再像旧表单页。",
      "gen_label_mode": "模式",
      "gen_label_material": "素材",
      "gen_label_status": "状态",
      "gen_uploading": "正在上传...",
      "gen_sheet_desc": "拍摄的内容为……（用于优化生成效果）",
      "gen_sheet_object": "物体",
      "gen_sheet_scene": "场景",
      "gen_preview_subtitle": "先检查图像气质，再决定是否提交到生成流程。",
      "gen_image_load_fail": "图片加载失败",
      "gen_regenerate_fail": "重新生成失败",
      "gen_submit_success": "提交成功，任务已创建",
      "gen_submit_fail": "提交失败",
      "gen_server_error": "服务器返回异常",
      "gen_select_image": "请先选择图片",
      "gen_select_video": "请先选择视频",
      "gen_enter_text": "请先输入描述文本",
      "gen_generate_fail": "生成失败",
      "gen_video_task_title": "任务类型",
      "gen_video_task_sheet_desc": "选择这段视频要走的生成路线",
      "gen_video_task_dual_chain": "视频双链",
      "gen_video_task_dual_chain_hint": "先快后精，适合默认使用",
      "gen_video_task_3dgs": "视频3DGS",
      "gen_video_task_3dgs_hint": "传统视频转 3DGS",
      "gen_video_task_feed_forward": "视频前馈3DGS",
      "gen_video_task_feed_forward_hint": "更快出结果的 3DGS",
      "gen_video_task_sugar": "视频SuGaR高质量",
      "gen_video_task_sugar_hint": "更高质量，但更慢",
      "gen_video_task_2dgs": "视频2DGS",
      "gen_video_task_2dgs_hint": "输出 2DGS 路线",
      "gen_video_task_sparse2dgs": "视频Sparse2DGS",
      "gen_video_task_sparse2dgs_hint": "抽帧后走 Sparse2DGS",
      "gen_text_pipeline_hint": "文字将先通过 AI 生成图片，再将生成的图片转化为三维记忆模型。",
      "gen_cancel_title": "操作进行中",
      "gen_cancel_message": "当前正在处理中，退出页面将丢失进度。\n确定要退出吗？",
      "gen_cancel_confirm": "确认退出",
      "gen_cancel_continue": "继续操作",
      "gen_video_too_large": "视频文件过大（最大 1.5 GB），请重新选择。",
      "gen_video_too_long": "视频时长过长（最长 10 分钟），请重新选择。",
      "gen_image_too_large": "图片文件过大（最大 20 MB），请重新选择。",
      // Login page
      "login_signup_success": "注册成功！请检查邮箱完成验证。",
      "login_success": "登录成功",
      "login_auth_fail": "认证失败",
      "login_error": "发生错误",
      "login_enter_home": "进入首页",
      "login_signup": "注册",
      "login_login": "登录",
      "login_create_account": "创建 Brain Dance 账号",
      "login_welcome": "登录 Brain Dance",
      "login_signup_hint": "注册后请前往邮箱完成验证。",
      "login_hint": "输入邮箱和密码继续。",
      "login_email": "邮箱",
      "login_email_hint": "请输入验证邮箱",
      "login_password": "密码",
      "login_password_hint": "请输入密码(至少6位)",
      "login_signup_btn": "注册新账号",
      "login_goto_login": "已有账号？去登录",
      "login_goto_signup": "没有账号？去注册",
      "login_admin_secret": "当前 .env 使用的是 secret key，应用已进入管理员模式。",
      "login_admin_rls": "管理员模式会绕过 RLS，可直接查看全部模型与任务。",
      // Record page
      "reco_motion_steady": "保持缓慢移动",
      "reco_motion_detail": "把手机当作滑轨，沿目标外圈匀速平移",
      "reco_app_switch": "应用切换导致录像中断，已保存录制内容",
      "reco_done": "录制完成",
      "reco_record_too_short": "拍摄失败，可能的原因：拍摄时长过短",
      "reco_save_fail": "无法保存视频到相册。视频文件暂存于缓存中，注意缓存清理。",
      "reco_save_error": "保存视频到相册时发生错误",
      "reco_hint_steady": "开始缓慢移动",
      "reco_hint_ideal": "速度合适，继续匀速扫描",
      "reco_hint_caution": "稍微有点快，再慢一点",
      "reco_hint_danger": "移动过快，请立刻放慢",
      "reco_detail_steady": "不要停太久，缓慢平移能让采样更连续",
      "reco_detail_ideal": "沿着目标外圈平滑移动，避免突然转向",
      "reco_detail_caution": "把步幅减小一些，尽量保持手腕稳定",
      "reco_detail_danger": "检测到明显抖动或突发加速，请像滑轨一样慢慢移动",
      "reco_accel_warning": "检测到加速度过大，请缓慢移动手机",
      "reco_scan_start": "开始扫描覆盖",
      "reco_scan_pause": "已暂停扫描",
      "reco_no_switch": "录像中无法直接切换传感器",
      "reco_scan_tip": "扫描提示",
      "reco_scan_before": "先把手机当作滑轨，再开始采集。",
      "reco_scan_ok": "知道了",
      "reco_state_steady": "偏静止",
      "reco_state_ideal": "平稳",
      "reco_state_caution": "稍快",
      "reco_state_danger": "过快",
      // Settings page
      "set_subtitle": "调整账户、偏好和本地设备行为，保持整套界面一致。",
      "set_label_ui": "界面",
      "set_label_lang": "语言",
      "set_label_style": "风格",
      "set_tab1_title": "界面与账户",
      "set_tab1_desc": "把常用偏好收在一个面板里，避免设置页重新掉回默认工具样式。",
      "set_tab2_title": "实验选项",
      "set_tab2_desc": "把调试项和试验参数集中放在一个区块里，避免和主流程混在一起。",
      "set_tab3_title": "关于与存储",
      "set_tab3_desc": "保留版本信息、本地缓存和清理入口，用更像档案页的方式展示。",
      "set_tab4_title": "扩展列表",
      "set_tab4_desc": "保留滚动测试内容，但外观切到新的面板系统里，避免这里还是默认列表气质。",
      "set_logout": "退出登录",
      "set_admin_enabled": "管理员模式已启用",
      "recall_task_list": "任务列表",
      "recall_recent_added": "近日新增",
      "set_lang_zh": "中文",
      "set_lang_en": "English",
      "set_current_language": "当前语言",
      "set_current_theme": "当前模式",
      "set_theme_day": "日间",
      "set_theme_night": "夜间",
      "set_theme_day_cn": "日间模式",
      "set_theme_night_cn": "夜间模式",
      // Recall page
      "recall_subtitle": "把空间、任务和检索线索压进同一条记忆流里。",
      "recall_label_space": "空间",
      "recall_label_processing": "处理中",
      "recall_label_rag": "RAG",
      "recall_summary_title": "空间档案概览",
      "recall_ready_spaces": "已就绪空间",
      "recall_unknown_error": "未知错误",
      "recall_server_error": "服务器返回异常",
      "recall_rename_model": "重命名模型",
      "recall_detail_model": "模型详情",
      "recall_detail_subtitle": "查看模型的详细信息",
      "recall_detail_created_at": "创建时间",
      "recall_detail_updated_at": "更新时间",
      "recall_detail_task_type": "任务类型",
      "recall_detail_quality_score": "质量评分",
      "recall_detail_local_size": "本地文件大小",
      "recall_detail_unknown": "未知",
      "recall_rename_subtitle": "修改模型的显示名称",
      "recall_rename_hint": "请输入新名称",
      "recall_rename_success": "重命名成功",
      "recall_rename_fail": "重命名失败",
      "recall_rename_invalid": "名称包含非法字符",
      "recall_download_model": "下载模型",
      "recall_download_model_start": "开始下载模型",
      "recall_download_model_success": "模型已保存",
      "recall_download_model_fail": "下载模型失败",
      "recall_download_model_unavailable": "当前模型暂不可下载",
      "recall_delete_local": "删除本地模型",
      "recall_delete_local_subtitle": "删除已下载的模型文件，释放存储空间",
      "recall_delete_local_success": "本地模型已删除",
      "recall_delete_local_fail": "删除本地模型失败",
      "recall_delete_local_none": "本地没有已下载的模型文件",
      "recall_share_to_community": "分享到社区",
      "recall_share_subtitle": "为这段记忆补上地点并发布到社区流",
      "recall_published": "已发布到社区",
      "recall_unnamed_model": "未命名模型",
      "recall_model_not_downloaded": "未下载模型",
      "recall_model_downloading": "已下载",
      "recall_model_available": "模型可用",
      // Community page
      "community_share_tooltip": "分享记忆",
      "community_joined": "记忆已加入社区流",
      "community_label_memories": "社区记忆",
      "community_label_memories_hint": "当前可浏览的空间贴文",
      "community_label_nodes": "地点节点",
      "community_label_nodes_hint": "地图上的可探索坐标",
      "community_tab_feed": "流式浏览",
      "community_tab_map": "地图探索",
      "community_map_hint": "点地图上的记忆节点，会展开同地点用户拍到的空间内容。",
      "community_enter_memory": "进入记忆",
      "community_location_content": "地点内容",
      "community_open_model": "打开当前模型",
      "community_view_location": "查看同地点内容",
      "community_empty_feed": "社区流暂时为空",
      "community_empty_hint": "先分享一个带地点的记忆模型，地图和流式浏览会同时出现。",
      "community_share_title": "分享你的地点记忆",
      "community_share_hint": "先选择一个你已有的模型，再给它补上地点和一句简短说明。",
      "community_select_model": "选择要分享的模型",
      "community_input_title": "标题",
      "community_input_caption": "这段记忆想让别人看到什么",
      "community_location_preset": "快速地点预设",
      "community_input_place": "地点名称",
      "community_input_lat": "纬度",
      "community_input_lng": "经度",
      "community_publishing": "发布中...",
      "community_publish": "发布到社区",
      "community_fill_all": "请把模型、标题、文案和地点都填完整",
      "community_unnamed_memory": "未命名记忆",
      "community_no_location": "未标注地点",
      "community_anonymous": "匿名用户",
      "community_unnamed_model": "未命名模型",
      // Video submit page
      "video_submit_title": "视频信息提交",
      "video_submit_name": "视频名称 (可选)",
      "video_submit_name_hint": "请输入视频名称",
      "video_submit_thumbnail": "视频缩略图",
      "video_submit_btn": "提交并上传",
      "video_upload_cancel_title": "正在上传",
      "video_upload_cancel_message": "视频正在上传中，是否取消上传？",
      "video_upload_cancel_confirm": "取消上传",
      "video_upload_cancel_continue": "继续上传",
      "video_exit_title": "退出视频提交",
      "video_exit_message": "即将退出视频提交界面。",
      "video_exit_delete_checkbox": "删除刚拍摄的视频文件",
      "video_exit_confirm": "确认退出",
      "video_exit_cancel": "取消",
      "network_disconnected": "互联网已断开，请检查网络连接",
      "network_session_expired": "登录已过期，请重新登录",
      // Common/shared
      "admin_mode_msg": "当前为管理员浏览模式，未绑定用户，暂不支持上传任务。",
      "not_logged_in": "未登录，即将跳转登录页面...",
      "login_cancelled": "登录已取消或未完成",
      "login_success_upload": "登录成功，开始上传",
      "platform_webview_unsupported": "当前平台不支持内嵌网页",
      "viewer_downloading_title": "正在下载云端模型...",
      "viewer_downloading_subtitle": "这只需下载一次，之后可离线查看",
      "viewer_stop_download": "停止下载",
      "create": "创作",
      "create_guide_subtitle": "选择一种方式开始创建新的记忆。",
      "create_record_desc": "使用相机拍摄并记录空间场景。",
      "create_generate_desc": "通过图片、文本或视频生成记忆模型。",
      "timepeeling": "时间切片",
      "coming_soon": "即将推出",
      "gen_text_generating": "正在生成中",
      "gen_text_preview_title": "文本生成结果预览",
      "gen_text_regenerate": "重新生成",
      "gen_text_confirm": "确认",
      // Local model
      "local_model_download_fail": "模型下载失败，请检查网络后重试",
      "local_model_load_fail": "模型加载失败，请重新尝试",
      "local_model_qa_fail": "问答失败，请重新提问",
      "local_model_download_success": "模型已下载到应用私有目录",
      "local_model_fill_url": "请先填写模型下载链接",
      "local_model_fill_path": "请先填写模型路径",
      "local_model_fill_question": "请输入要提问的问题",
      "local_model_load_first": "请先加载本地模型",
      // Cloud model
      "cloud_model_delete_success": "云端模型删除成功",
      "cloud_model_delete_fail": "云端模型删除失败，请重试",
      "cloud_model_missing_id": "模型数据异常，无法删除",
      "cloud_model_no_permission": "只能删除自己的云端模型",
      // Viewer
      "viewer_download_fail": "模型下载失败，请重试",
      "viewer_spark_error": "渲染服务异常，请稍后重试",
    },
  ),
  en(
    name: "English",
    map: {
      "sensor_off": "Sensor Off",
      'sensor_on': "Sensor On",
      "lang": "English",
      "locale": "en_US",
      "title": "Brain Dance",
      "home_page": "Brain Dance",
      "pick_null": "Please select",
      "set_lang": "Language (Tap to switch)",
      "set_night": "Night Mode",
      "set_ver": "Version",
      "set_pub": "Publish Date",
      "set_cache": "Clear Cache",
      "set_tab1": "Display",
      "set_tab2": "Video",
      "set_tab3": "App",
      "set_tab4": "Help",
      "gen_top": "Generate from",
      "gen_pic": "Image",
      "gen_text": "Text",
      "gen_video": "Video",
      "gen_tip_pic": "Please select an image file (less than [FILE_SIZE])",
      "gen_tip_text": "Please enter a description text",
      "gen_tip_video":
          "Please select a video file\n(Size ≤ 1.5 GB,\nDuration within 10 minutes)",
      "gen_tip_textbox": "Type text here",
      "gen_button": "Generate Memory",
      "gen_shot": "Use Camera",
      "gen_gallery": "Choose from Gallery",
      "gen_cancel": "Cancel",
      "reco_tip_title1": "1. Equipment & Settings",
      "reco_tip_title2": "2. Shooting Environment & Operation",
      "reco_tip_title3": "3. Post-Shooting Check",
      "reco_tip1":
          """Device: Use a smartphone or camera that supports 1080p/30fps video recording.
Stability: It is recommended to use a tripod to avoid shaky footage.
Resolution & Frame Rate: Manually select 1920x1080 (1080p) and 30fps in the settings.
Exposure: Use auto-exposure mode. If there are significant changes in lighting, manually lock the exposure.
Focus: Use continuous auto-focus mode.""",
      "reco_tip2":
          """Lighting: Shoot under even and sufficient lighting. Avoid backlighting (e.g., having a window as the background).
Movement: During shooting, try to avoid rapid movements or shaking of the camera.
Content: Plan diverse shooting content and angles to avoid repetitive footage.""",
      "reco_tip3":
          """If the video was shot using a phone's built-in camera app, use editing software (e.g., CapCut) to review the video and trim any shaky, blurry, or overexposed segments.
When finally exporting, confirm the settings are 1080p and 30fps.""",
      "reco_camun":
          "Cannot access the camera.\nPlease check and grant the camera permission in your device settings to continue.",
      "set_open_settings": "Open Settings",
      "reco_wait": "Initializing the camera...",
      "recall": "Recall",
      "record": "Record",
      "generate": "Generate",
      "community": "Community",
      "settings": "Settings",
      "manage": "Manage",
      "tip_unava": "This feature is not yet available, stay tuned!",
      "tip_oversize": "Uploaded file(s) are too large!",
      "tip_overquan": "You have uploaded too many files!",
      "tip_cache": "The cache is successfully cleared",
      "tip_fail": "Failed to upload file(s)!",
      "tip_no_permission": "Does not have permission to save to the gallery.",
      "recall_search_hint": "Search memories...",
      "recall_empty_title":
          "No memories yet, go record some beautiful moments!",
      "recall_open_demo": "Open local offline Demo model",
      "recall_no_desc": "No description available",
      "recall_demo_title": "Local Demo Model (Available Offline)",
      "recall_demo_desc":
          "Pre-installed 3DGS model, viewable without network connectivity.",
      "recall_error_offline":
          "Failed to load models, switched to offline mode.",
      "recall_error_search": "Search failed: ",
      "recall_refresh": "Refresh",
      "recall_local_rag": "On-device private search",
      "recall_cloud_rag": "Cloud semantic search",
      "recall_local_ai_rag": "Local AI Q&A",
      "recall_agent_rag": "Spatial Memory Agent",
      "recall_search_mode": "Search mode",
      "recall_search_mode_desc":
          "Choose the memory retrieval and intelligent management mode used by this search bar.",
      "recall_local_ready": "Local index ready",
      "recall_local_indexing": "Building on-device vector index...",
      "recall_local_scope": "Search terms stay on this device",
      "recall_local_ai_scope":
          "Questions use local memory retrieval and on-device answering",
      "recall_agent_scope":
          "Use the Supabase Deno LangChain toolchain to retrieve, navigate, analyze and manage 3D memories",
      "recall_local_empty": "No local matches found in the memory index",
      "recall_cloud_scope": "Search terms will be sent to the cloud model",
      "recall_cloud_empty": "No results returned from cloud semantic search",
      "recall_local_ai_empty":
          "Local AI could not retrieve memory snippets for answering",
      "recall_agent_empty":
          "Ask a spatial question or management task, and the agent will handle your 3D memories with multiple tools",
      "recall_local_ai_hint": "Ask a question using local memory...",
      "recall_agent_hint":
          "Ask a spatial question or management command, for example: \"Take me to the kitchen and compare recent changes\"",
      "recall_agent_panel_hint":
          "Press Enter after your prompt. The agent will use multiple tools to retrieve, navigate and manage your 3D memories.",
      "agent_status_connecting": "Connecting to the agent...",
      "agent_status_stopped": "Agent execution stopped",
      "agent_status_stopped_summary":
          "This agent run was stopped manually by the user",
      "agent_status_force_interrupted": "The agent was forcefully interrupted",
      "agent_status_final_answer_ready": "Final answer generated",
      "agent_status_plan_ready": "Execution plan generated",
      "agent_status_tool_start": "Starting tool execution",
      "agent_status_waiting_tool_result": "Waiting for tool result",
      "agent_status_tool_result_ready": "Tool result received",
      "agent_status_generating_final_answer": "Generating final answer",
      "agent_status_execution_failed": "Agent execution failed",
      "agent_status_request_started": "Starting the agent streaming request",
      "agent_status_stream_fallback":
          "Streaming connection failed, falling back to a standard request",
      "agent_status_stream_start_fallback":
          "Streaming startup failed, falling back to a standard request",
      "agent_status_single_response_fallback":
          "Streaming events are unavailable in this environment, so the agent fell back to a single response",
      "agent_status_tool_call": "Tool call",
      "agent_status_tool_args": "Arguments",
      "agent_status_tool_unnamed": "Unnamed tool",
      "agent_status_warming_up": "Warming up the neural engine...",
      "agent_status_reviewing_context": "Reviewing related context...",
      "agent_status_deep_thinking": "Reasoning deeply...",
      "agent_action_copy": "Copy",
      "agent_action_stop": "Stop",
      "agent_action_code_copied": "Code copied",
      "agent_elapsed_running": "Agent running for {duration}",
      "agent_elapsed_finished": "Total agent duration {duration}",
      "agent_search_failed": "Agent operation failed",
      "agent_stream_failed": "Agent streaming failed (falling back)",
      "agent_stream_start_failed":
          "Agent stream startup failed (falling back)",
      "agent_error_empty_query": "Query cannot be empty",
      "agent_error_missing_supabase_url":
          "SUPABASE_URL is not configured, so the agent stream cannot be opened",
      "agent_error_bad_response": "agent-recall returned an invalid response",
      "agent_error_unavailable":
          "agent-recall is currently unavailable (HTTP 503). This usually means the Edge Function worker failed to start or the upstream model gateway is temporarily unavailable. Check the Supabase Edge Function logs first.",
      "agent_error_upstream":
          "The upstream service for agent-recall returned an abnormal response. Check the Edge Function logs and model gateway configuration.",
      "agent_error_http": "agent-recall request failed (HTTP {status})",
      // Task list page
      "task_list_title": "Memory Tasks",
      "task_list_empty_title": "No Tasks",
      "task_list_empty_desc": "Start recording your first memory!",
      "status_pending": "Pending",
      "status_processing": "Processing",
      "status_completed": "Completed",
      "status_failed": "Failed",
      "error_not_logged_in": "Please log in first",
      "error_fetch_tasks": "Failed to fetch tasks",
      "error_title": "Error Occurred",
      "error_unknown": "Unknown error",
      "retry": "Retry",
      "refresh": "Refresh",
      "task_status_pending": "Task is pending...",
      "task_status_processing": "Task is processing...",
      "task_status_completed": "Task completed",
      "task_status_failed": "Task failed",
      "task_status_unknown": "Unknown task status",
      // Task notification popup
      "task_completed": "task(s) completed",
      "task_failed": "task(s) failed",
      "task_notification_completed": "memory task(s) completed, tap to view",
      "task_notification_failed": "memory task(s) failed, tap to view",
      "logs_collapse": "Collapse logs",
      "logs_expand": "Expand logs",
      // Generate page
      "gen_upload_progress": "Upload %s%",
      "gen_waiting_material": "Waiting for material",
      "gen_ready_submit": "Ready",
      "gen_section_image": "Image Input",
      "gen_section_text": "Text Draft",
      "gen_section_video": "Video Capture",
      "gen_subtitle":
          "Combine materials, status and submission into one unified generation flow.",
      "gen_label_mode": "Mode",
      "gen_label_material": "Material",
      "gen_label_status": "Status",
      "gen_uploading": "Uploading...",
      "gen_sheet_desc": "Content type... (for optimizing generation)",
      "gen_sheet_object": "Object",
      "gen_sheet_scene": "Scene",
      "gen_preview_subtitle":
          "Check the image quality before submitting to the generation pipeline.",
      "gen_image_load_fail": "Failed to load image",
      "gen_regenerate_fail": "Regeneration failed",
      "gen_submit_success": "Submitted successfully, task created",
      "gen_submit_fail": "Submission failed",
      "gen_server_error": "Server returned an error",
      "gen_select_image": "Please select an image first",
      "gen_select_video": "Please select a video first",
      "gen_enter_text": "Please enter description text first",
      "gen_generate_fail": "Generation failed",
      "gen_video_task_title": "Task Type",
      "gen_video_task_sheet_desc":
          "Choose the generation pipeline for this video",
      "gen_video_task_dual_chain": "Video Dual Chain",
      "gen_video_task_dual_chain_hint": "Fast first, then refine",
      "gen_video_task_3dgs": "Video 3DGS",
      "gen_video_task_3dgs_hint": "Classic video to 3DGS",
      "gen_video_task_feed_forward": "Video Feed-Forward 3DGS",
      "gen_video_task_feed_forward_hint": "Faster 3DGS generation",
      "gen_video_task_sugar": "Video SuGaR High Quality",
      "gen_video_task_sugar_hint": "Higher quality, slower",
      "gen_video_task_2dgs": "Video 2DGS",
      "gen_video_task_2dgs_hint": "2DGS output pipeline",
      "gen_video_task_sparse2dgs": "Video Sparse2DGS",
      "gen_video_task_sparse2dgs_hint": "Sample frames into Sparse2DGS",
      "gen_text_pipeline_hint": "Text will first generate an image via AI, then the image will be converted into a 3D memory model.",
      "gen_cancel_title": "Operation in Progress",
      "gen_cancel_message": "Processing is underway. Exiting will lose progress.\nAre you sure you want to exit?",
      "gen_cancel_confirm": "Exit",
      "gen_cancel_continue": "Continue",
      "gen_video_too_large": "Video file is too large (max 1.5 GB). Please select another one.",
      "gen_video_too_long": "Video duration is too long (max 10 min). Please select another one.",
      "gen_image_too_large": "Image file is too large (max 20 MB). Please select another one.",
      // Login page
      "login_signup_success":
          "Registration successful! Please check your email to verify.",
      "login_success": "Login successful",
      "login_auth_fail": "Authentication failed",
      "login_error": "An error occurred",
      "login_enter_home": "Enter Home",
      "login_signup": "Sign Up",
      "login_login": "Log In",
      "login_create_account": "Create Brain Dance Account",
      "login_welcome": "Log in to Brain Dance",
      "login_signup_hint": "Please verify your email after registration.",
      "login_hint": "Enter email and password to continue.",
      "login_email": "Email",
      "login_email_hint": "Enter your email",
      "login_password": "Password",
      "login_password_hint": "Enter password (min 6 chars)",
      "login_signup_btn": "Create Account",
      "login_goto_login": "Have an account? Log in",
      "login_goto_signup": "No account? Sign up",
      "login_admin_secret":
          "Current .env uses secret key, app is in admin mode.",
      "login_admin_rls":
          "Admin mode bypasses RLS, allowing access to all models and tasks.",
      // Record page
      "reco_motion_steady": "Keep moving slowly",
      "reco_motion_detail":
          "Move the phone like a slider, along the target's outer edge",
      "reco_app_switch": "Recording interrupted by app switch, content saved",
      "reco_done": "Recording completed",
      "reco_record_too_short": "Recording failed, possible reason: recording too short",
      "reco_save_fail":
          "Cannot save video to gallery. Video is temporarily cached.",
      "reco_save_error": "Error saving video to gallery",
      "reco_hint_steady": "Start moving slowly",
      "reco_hint_ideal": "Good speed, continue steady scanning",
      "reco_hint_caution": "A bit fast, slow down a little",
      "reco_hint_danger": "Moving too fast, slow down immediately",
      "reco_detail_steady":
          "Don't stop too long, slow panning keeps sampling continuous",
      "reco_detail_ideal":
          "Move smoothly around the target, avoid sudden turns",
      "reco_detail_caution": "Reduce stride, keep your wrist steady",
      "reco_detail_danger":
          "Significant shake detected, move slowly like a slider",
      "reco_accel_warning":
          "Excessive acceleration detected, move phone slowly",
      "reco_scan_start": "Start scanning",
      "reco_scan_pause": "Scanning paused",
      "reco_no_switch": "Cannot switch sensor while recording",
      "reco_scan_tip": "Scan Tips",
      "reco_scan_before":
          "Move the phone like a slider before starting capture.",
      "reco_scan_ok": "Got it",
      "reco_state_steady": "Steady",
      "reco_state_ideal": "Smooth",
      "reco_state_caution": "Slightly fast",
      "reco_state_danger": "Too fast",
      // Settings page
      "set_subtitle":
          "Adjust account, preferences and device settings for a consistent experience.",
      "set_label_ui": "UI",
      "set_label_lang": "Language",
      "set_label_style": "Style",
      "set_tab1_title": "UI & Account",
      "set_tab1_desc": "Keep common preferences in one panel.",
      "set_tab2_title": "Experimental",
      "set_tab2_desc": "Keep debug and experimental parameters in one section.",
      "set_tab3_title": "About & Storage",
      "set_tab3_desc": "Version info, local cache and cleanup options.",
      "set_tab4_title": "Extensions",
      "set_tab4_desc": "Scroll test content in the new panel system.",
      "set_logout": "Log Out",
      "set_admin_enabled": "Admin Mode Enabled",
      "set_lang_zh": "中文",
      "set_lang_en": "English",
      "set_current_language": "Current Language",
      "set_current_theme": "Current Mode",
      "set_theme_day": "DAY",
      "set_theme_night": "NIGHT",
      "set_theme_day_cn": "Day Mode",
      "set_theme_night_cn": "Night Mode",
      // Recall page
      "recall_subtitle":
          "Combine spaces, tasks and search clues into one memory stream.",
      "recall_label_space": "Spaces",
      "recall_label_processing": "Processing",
      "recall_label_rag": "RAG",
      "recall_summary_title": "Spatial Archive Overview",
      "recall_task_list": "Task List",
      "recall_recent_added": "Recently Added",
      "recall_ready_spaces": "Ready Spaces",
      "recall_unknown_error": "Unknown error",
      "recall_server_error": "Server returned an error",
      "recall_rename_model": "Rename Model",
      "recall_detail_model": "Model Details",
      "recall_detail_subtitle": "View detailed model information",
      "recall_detail_created_at": "Created",
      "recall_detail_updated_at": "Updated",
      "recall_detail_task_type": "Task Type",
      "recall_detail_quality_score": "Quality Score",
      "recall_detail_local_size": "Local File Size",
      "recall_detail_unknown": "Unknown",
      "recall_rename_subtitle": "Change the display name of this model",
      "recall_rename_hint": "Enter new name",
      "recall_rename_success": "Renamed successfully",
      "recall_rename_fail": "Rename failed",
      "recall_rename_invalid": "Name contains invalid characters",
      "recall_download_model": "Download Model",
      "recall_download_model_start": "Starting model download",
      "recall_download_model_success": "Model saved",
      "recall_download_model_fail": "Failed to download model",
      "recall_download_model_unavailable": "This model is not downloadable yet",
      "recall_delete_local": "Delete Local Model",
      "recall_delete_local_subtitle":
          "Remove downloaded model files to free storage",
      "recall_delete_local_success": "Local model deleted",
      "recall_delete_local_fail": "Failed to delete local model",
      "recall_delete_local_none": "No local model files found",
      "recall_share_to_community": "Share to Community",
      "recall_share_subtitle": "Add location and publish to community feed",
      "recall_published": "Published to community",
      "recall_unnamed_model": "Unnamed model",
      "recall_model_not_downloaded": "Model not downloaded",
      "recall_model_downloading": "Downloaded",
      "recall_model_available": "Model available",
      // Community page
      "community_share_tooltip": "Share Memory",
      "community_joined": "Memory added to community feed",
      "community_label_memories": "Community Memories",
      "community_label_memories_hint": "Spatial posts available for browsing",
      "community_label_nodes": "Location Nodes",
      "community_label_nodes_hint": "Explorable coordinates on the map",
      "community_tab_feed": "Feed",
      "community_tab_map": "Map Explore",
      "community_map_hint":
          "Tap memory nodes on the map to view spatial content from the same location.",
      "community_enter_memory": "Enter Memory",
      "community_location_content": "Location Content",
      "community_open_model": "Open Current Model",
      "community_view_location": "View Same Location",
      "community_empty_feed": "Community feed is empty",
      "community_empty_hint": "Share a memory model with a location first.",
      "community_share_title": "Share Your Location Memory",
      "community_share_hint":
          "Select a model, then add location and a brief description.",
      "community_select_model": "Select Model to Share",
      "community_input_title": "Title",
      "community_input_caption": "What do you want others to see",
      "community_location_preset": "Quick Location Presets",
      "community_input_place": "Place Name",
      "community_input_lat": "Latitude",
      "community_input_lng": "Longitude",
      "community_publishing": "Publishing...",
      "community_publish": "Publish to Community",
      "community_fill_all": "Please complete all fields",
      "community_unnamed_memory": "Unnamed Memory",
      "community_no_location": "No Location",
      "community_anonymous": "Anonymous",
      "community_unnamed_model": "Unnamed Model",
      // Video submit page
      "video_submit_title": "Video Submission",
      "video_submit_name": "Video Name (Optional)",
      "video_submit_name_hint": "Enter video name",
      "video_submit_thumbnail": "Video Thumbnail",
      "video_submit_btn": "Submit & Upload",
      "video_upload_cancel_title": "Uploading",
      "video_upload_cancel_message": "Video upload is in progress. Do you want to cancel?",
      "video_upload_cancel_confirm": "Cancel Upload",
      "video_upload_cancel_continue": "Continue Upload",
      "video_exit_title": "Exit Video Submission",
      "video_exit_message": "You are about to leave the video submission page.",
      "video_exit_delete_checkbox": "Delete the recorded video file",
      "video_exit_confirm": "Exit",
      "video_exit_cancel": "Cancel",
      "network_disconnected": "Internet disconnected. Please check your network connection.",
      "network_session_expired": "Session expired. Please re-login.",
      // Common/shared
      "admin_mode_msg":
          "Admin browse mode, no user bound. Upload not supported.",
      "not_logged_in": "Not logged in, redirecting to login...",
      "login_cancelled": "Login cancelled or incomplete",
      "login_success_upload": "Login successful, starting upload",
      "platform_webview_unsupported":
          "Embedded webview not supported on this platform",
      "viewer_downloading_title": "Downloading cloud model...",
      "viewer_downloading_subtitle": "Only needed once, then available offline",
      "viewer_stop_download": "Stop",
      "create": "Create",
      "create_guide_subtitle": "Choose a way to create a new memory.",
      "create_record_desc":
          "Use the camera to capture and record spatial scenes.",
      "create_generate_desc":
          "Generate memory models from images, text, or video.",
      "timepeeling": "Time Peeling",
      "coming_soon": "Coming soon",
      "gen_text_generating": "Generating...",
      "gen_text_preview_title": "Text Generation Preview",
      "gen_text_regenerate": "Regenerate",
      "gen_text_confirm": "Confirm",
      // Local model
      "local_model_download_fail": "Model download failed. Please check your network and retry.",
      "local_model_load_fail": "Model loading failed. Please try again.",
      "local_model_qa_fail": "Q&A failed. Please try again.",
      "local_model_download_success": "Model downloaded to app storage.",
      "local_model_fill_url": "Please enter the model download URL first.",
      "local_model_fill_path": "Please enter the model file path first.",
      "local_model_fill_question": "Please enter your question.",
      "local_model_load_first": "Please load a local model first.",
      // Cloud model
      "cloud_model_delete_success": "Cloud model deleted.",
      "cloud_model_delete_fail": "Failed to delete cloud model. Please try again.",
      "cloud_model_missing_id": "Model data is invalid, cannot delete.",
      "cloud_model_no_permission": "You can only delete your own cloud models.",
      // Viewer
      "viewer_download_fail": "Model download failed. Please try again.",
      "viewer_spark_error": "Rendering service error. Please try again later.",
    },
  );

  const Language({required this.name, required this.map});
  final String name;
  final Map<String, String> map;
}

class Localize {
  static Map<String, String> getLangMap(String localeCode) {
    for (var lang in Language.values) {
      if (lang.map['locale'] == localeCode) {
        return lang.map;
      }
    }
    return Language.en.map; // Default to English if not found
  }
}
